### ISSUE TITLE
it doesn't work (am i doing something wrong?)

### ISSUE THREAD

**Issue by LV8HDT** [dropcreations/Manzana-Apple-Music-Tagger#2]
```
Microsoft Windows [Version 10.0.22621.1702]
(c) Microsoft Corporation. All rights reserved.

C:\Users\leona\Downloads\2Pac\The Don Killuminati The 7 Day Theory>C:\Users\leona\Downloads\Manzana-Apple-Music-Tagger-main\manzana.py https://music.apple.com/us/album/the-don-killuminati-the-7-day-theory/1588164338

[22:29:38] [Downloader] INFO: Proccessing media...
[22:29:38] [AppleMusic] INFO: Loading cache...
[22:29:38] [AppleMusic] INFO: Checking access token found in cache...
[22:29:38] [AppleMusic] INFO: Loading cookies...
[22:29:38] [AppleMusic] INFO: Getting API response...
[22:29:39] [AppleMusic] INFO: Fetching album info...
Traceback (most recent call last):
  File "C:\Users\leona\Downloads\Manzana-Apple-Music-Tagger-main\manzana.py", line 201, in <module>
    main()
  File "C:\Users\leona\Downloads\Manzana-Apple-Music-Tagger-main\manzana.py", line 188, in main
    cover = download_artwork(data)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\Downloads\Manzana-Apple-Music-Tagger-main\manzana.py", line 71, in download_artwork
    if info["externalCover"].get("originalUrl") is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

This is the error I get. Maybe I'm doing something wrong?

**Comment by dropcreations** [comment]
@LV8HDT There has an error in the script. I'll fix it. Thank you for the issue.

**Comment by dropcreations** [comment]
@LV8HDT The issue was for some albums only. Now I have fixed it and updated the script. Now you can try your album. So, if you have any other issues please mention. Thank you.
